version: "3"
services:
  jupyter:
    build: .
    ports:
      - "8888:8888"
    links:
      - pg

  pg:
    image: postgres
    # Expose port to host for local development
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_pass
      POSTGRES_DB: data
