IMDB_ID = 'id'
IMDB_ID2 = 'imdb_id'
IMDB_ORIGINAL_TITLE = 'original_title'
IMDB_BUDGET = 'budget'
IMDB_REVENUE = 'revenue'
IMDB_PROD_COMP = 'production_companies'

WIKI_TITLE = 'title'
WIKI_URL = 'url'
WIKI_ABSTRACT = 'abstract'
